### ISSUE TITLE
Gmaps support in Jupyter Notebooks in Databricks

### ISSUE THREAD

**Issue by lokijota** [pbugnion/gmaps#257]
Hi,

I've tried using gmaps inside Databricks but the clusters stop running pythonn, resuming normal behaviour when I delete gmaps. Do you know if this can be made to work? the errors I get are:

/databricks/python/lib/python3.5/site-packages/IPython/config/loader.py:38: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils.traitlets import HasTraits, List, Any, TraitError
Traceback (most recent call last):
  File "/tmp/1529273180558-0/PythonShell.py", line 27, in <module>
    from IPython.nbconvert.filters.ansi import ansi2html
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/export.py", line 23, in <module>
    from .templateexporter import TemplateExporter
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 31, in <module>
    from IPython.nbconvert import filters
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/filters/markdown.py", line 25, in <module>
    from IPython.nbconvert.utils.pandoc import pandoc
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/utils/pandoc.py", line 24, in <module>
    from IPython.utils.process import is_cmd_found, FindCmdError
ImportError: cannot import name 'is_cmd_found'
/databricks/python/lib/python3.5/site-packages/IPython/config/loader.py:38: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils.traitlets import HasTraits, List, Any, TraitError
Traceback (most recent call last):
  File "/tmp/1529273180558-0/PythonShell.py", line 27, in <module>
    from IPython.nbconvert.filters.ansi import ansi2html
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/__init__.py", line 3, in <module>
    from .exporters import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/__init__.py", line 1, in <module>
    from .export import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/export.py", line 23, in <module>
    from .templateexporter import TemplateExporter
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 31, in <module>
    from IPython.nbconvert import filters
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/filters/markdown.py", line 25, in <module>
    from IPython.nbconvert.utils.pandoc import pandoc
  File "/databricks/python/lib/python3.5/site-packages/IPython/nbconvert/utils/pandoc.py", line 24, in <module>
    from IPython.utils.process import is_cmd_found, FindCmdError
ImportError: cannot import name 'is_cmd_found'

**Comment by pbugnion** [comment]
Thanks for raising this. Answers to the following would be helpful so I can get a better picture.

1. You seem to be getting a lot of errors related to `nbconvert`. Any thoughts on why that would be? 
Were you running nbconvert?

2. What version of the notebook does Databricks run? Posting a screenshot of *Help* > *About* in the Jupyter menu would be useful.

3. Does ipywidgets work? If you run `import ipywidgets as widgets; widgets.IntSlider()`, what do you see? (you may need to `pip install ipywidgets`).

4. How did you install gmaps? With pip or from conda-forge?
