### ISSUE TITLE
gmap demo error.

### ISSUE THREAD

**Issue by Shaba1** [pbugnion/gmaps#306]

**Comment by Shaba1** [comment]
I tried to run the taxi route demo for gmaps from this page:

https://github.com/pbugnion/gmaps

I am using 
Windows 10 premium 64 bit
Google chrome vVersion 75.0.3770.100 (Official Build) (64-bit)
python 2.7.7 32 bit 
and I have a valid GOOGLE API key

when I run the demo I get this


Traceback (most recent call last):
  File "c:\Users\<USER NAME>\Desktop\My Projects\Sqlite Docs\gmap demo1.py", line 6, in <module>
    locations = gmaps.datasets.load_dataset("taxi_rides")
  File "C:\Python27\lib\site-packages\gmaps\datasets\datasets.py", line 124, in load_dataset
    f = urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by Shaba1** [comment]
duplicate post
