### ISSUE TITLE
AttributeError: DOMWidget when trying sudo pip install gmaps  

### ISSUE THREAD

**Issue by shiv12095** [pbugnion/gmaps#48]
I am trying to install gmaps using pip on ubuntu 14.04

However I am getting the following issue

```
Collecting gmaps
  Downloading gmaps-0.1.6.tar.gz (98kB)
    100% |████████████████████████████████| 102kB 75kB/s 
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
      "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
    /usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
      warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-3069XK/gmaps/setup.py", line 7, in <module>
        import gmaps
      File "gmaps/__init__.py", line 3, in <module>
        from heatmap import heatmap
      File "gmaps/heatmap.py", line 8, in <module>
        class HeatmapWidget(widgets.DOMWidget):
      File "/usr/local/lib/python2.7/dist-packages/IPython/utils/shimmodule.py", line 92, in __getattr__
        raise AttributeError(key)
    AttributeError: DOMWidget
    
```

**Comment by pbugnion** [comment]
Are you using IPython 4?

You can find out by typing `ipython --version` in a terminal.

**Comment by pbugnion** [comment]
I've now released version 0.2.0 on PyPi, which is compatible with IPython 4.

**Comment by shiv12095** [comment]
I am using ipython version 4.0.1

Tried installing gmaps 0.2.0
Got another issue

```
Collecting gmaps
  Downloading gmaps-0.2.0.tar.gz (97kB)
    100% |████████████████████████████████| 98kB 102kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-L_z1hR/gmaps/setup.py", line 6, in <module>
        import gmaps
      File "gmaps/__init__.py", line 3, in <module>
        from gmaps.heatmap import heatmap
      File "gmaps/heatmap.py", line 4, in <module>
        from ._ipywidgets import widgets
      File "gmaps/_ipywidgets.py", line 17, in <module>
        from ipywidgets import widgets
    ImportError: No module named ipywidgets
    
    ----------------------------------------
```

**Comment by constcast** [comment]
Did you install Jupyter? What does 

    jupyter --version

say?

**Comment by shiv12095** [comment]
I hadn't installed jupyter. 

Installed it now
```
 jupyter --version
4.0.6

```

Installing jupyter solved the issue. 

```
Collecting gmaps
  Downloading gmaps-0.2.0.tar.gz (97kB)
    100% |████████████████████████████████| 98kB 91kB/s 
Installing collected packages: gmaps
  Running setup.py install for gmaps
Successfully installed gmaps-0.2.0
```

Thanks a lot
