### ISSUE TITLE
gmaps is not a valid nbextension

### ISSUE THREAD

**Issue by timgrossmann** [pbugnion/gmaps#92]
jupyter nbextension enable --py gmaps

Traceback (most recent call last):
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 961, in start
    super(NBExtensionApp, self).start()
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 869, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 845, in toggle_nbextension_python
    logger=self.log)
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 374, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/TG/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 1135, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module gmaps is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'

**Comment by pbugnion** [comment]
gmaps definitely has a `_jupyter_nbextension_paths()` function. 

Can you provide more context? How did you install `gmaps`? Via pip? What version of the notebook are you running?

**Comment by timgrossmann** [comment]
jupyter --version
4.2.0

jupyter nbextension --version
4.2.3

pip install -U jupyter just prints:
Requirement already up-to-date: functools32; python_version == "2.7" in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook->jupyter)

**Comment by pbugnion** [comment]
How did you install gmaps? What does `pip list | grep gmaps` give?

**Comment by timgrossmann** [comment]
I just did "pip install gmaps"

pip list | grep gmaps
gmaps (0.3.5)
python-gmaps (0.3.1)

**Comment by pbugnion** [comment]
Ah -- I see. I suspect that `gmaps` (this repo) and `python-gmaps` (something else) are both installed under the same namespace. When it tries to install the JS extensions for the notebooks, it is looking in python-gmaps. Can you try installing just `gmaps` in a virtual environment?

**Comment by timgrossmann** [comment]
i uninstalled both and reinstalled just gmaps. 
Works perfectly now! 

Thank you so much.
